name: CI/CD Tournament Platform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Step 1: Backend Verification
  backend-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: cd backend && npm install

  # Step 2: Frontend Verification
  frontend-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: cd frontend && npm install
      - name: Build Angular
        run: cd frontend && npm run build # Valida errores de TS y memoria

  # Step 3: Deployment
  deploy:
    needs: [backend-ci, frontend-ci]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend
        run: curl -X POST ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}
      - name: Deploy Frontend
        run: curl -X POST ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}
